#!/usr/bin/env bash

PHP_CS_FIXER="vendor/bin/php-cs-fixer"
HAS_PHP_CS_FIXER=false
PHP_CS_FIXER_OPTIONS="--config=.php_cs"
MAX_ARG_LEN=8000

if [ -x vendor/bin/php-cs-fixer ]; then
    HAS_PHP_CS_FIXER=true
fi

if $HAS_PHP_CS_FIXER; then
    FILES=`git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3-`
    if [ ${#FILES} -gt $MAX_ARG_LEN ]; then
        readarray -t LINES <<< "$FILES"
        index=0
        batch=50
        while [ $index -lt ${#LINES[@]} ]; do
            $PHP_CS_FIXER fix $PHP_CS_FIXER_OPTIONS ${LINES[@]:$index:$batch}
            git add ${LINES[@]:$index:$batch}
            (( index = $index + $batch ))
        done
    elif [ -n "$FILES" ]; then
        $PHP_CS_FIXER fix $PHP_CS_FIXER_OPTIONS $FILES
        git add $FILES
    fi
else
    echo ""
    echo "php-cs-fixer was not found, please run:"
    echo ""
    echo "  composer update --dev"
    echo ""
fi
